/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Authors {
  id: Generated<number | null>;
  libris_id: string;
  life_span: string | null;
  name: string;
  slug: string;
}

export interface BookCovers {
  book_id: number;
  host: string;
  id: Generated<number | null>;
  image_id: string;
}

export interface Books {
  author_id: number;
  id: Generated<number | null>;
  instances: Generated<number>;
  pages: number;
  slug: string;
  title: string;
  year: number;
}

export interface Goodreads {
  avg_rating: number;
  book_id: number | null;
  book_url: string;
  id: Generated<number | null>;
  ratings: number;
}

export interface DB {
  authors: Authors;
  book_covers: BookCovers;
  books: Books;
  goodreads: Goodreads;
}
