name: "Cache Elm packages"
description: "Caches all packages in ~/.elm"

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v6
      id: elm-cache
      with:
        path: ~/.elm
        key: elm-${{ hashFiles('**/elm.json') }}